import type { DemoState } from "./types";

export function createSeedState(): DemoState {
  return {
    tenantName: "Brew Express",
    currency: "USD",
    taxRate: 0.08,
    nextOrderNumber: 2048,
    staff: [
      {
        id: "s1",
        staffCode: "101",
        name: "John Doe",
        role: "admin",
        active: true,
        pin: "1234",
        isDefaultPin: false,
      },
      {
        id: "s2",
        staffCode: "104",
        name: "Sarah Smith",
        role: "waiter",
        active: true,
        pin: "2222",
        isDefaultPin: false,
      },
      {
        id: "s3",
        staffCode: "201",
        name: "Chef Carlos",
        role: "kitchen",
        active: true,
        pin: "0000",
        isDefaultPin: true,
      },
      {
        id: "s4",
        staffCode: "105",
        name: "Jane Miller",
        role: "waiter",
        active: false,
        pin: "3333",
        isDefaultPin: false,
      },
      {
        id: "s5",
        staffCode: "106",
        name: "Mark Evans",
        role: "waiter",
        active: true,
        pin: "4444",
        isDefaultPin: false,
      },
    ],
    sections: [
      { id: "sec-main", name: "Main Floor" },
      { id: "sec-patio", name: "Patio" },
      { id: "sec-vip", name: "VIP Room" },
    ],
    fixtures: [
      { id: "fx-win", sectionId: "sec-main", kind: "windows", label: "Windows", x: 4, y: 4, w: 70, h: 10 },
      { id: "fx-bar", sectionId: "sec-main", kind: "bar", label: "Bar", x: 82, y: 16, w: 14, h: 60 },
      { id: "fx-ent", sectionId: "sec-main", kind: "entrance", label: "Entrance", x: 4, y: 86, w: 18, h: 8 },
      { id: "fx-kit", sectionId: "sec-main", kind: "kitchen", label: "Kitchen pass", x: 82, y: 78, w: 14, h: 14 },
    ],
    tables: [
      { id: "t1", sectionId: "sec-main", label: "Window 2", seats: 2, shape: "round", x: 8, y: 18, status: "empty" },
      { id: "t2", sectionId: "sec-main", label: "Window 4", seats: 2, shape: "round", x: 22, y: 18, status: "occupied" },
      { id: "t3", sectionId: "sec-main", label: "Booth A", seats: 4, shape: "rect", x: 8, y: 42, status: "empty" },
      { id: "t4", sectionId: "sec-main", label: "Booth B", seats: 4, shape: "rect", x: 28, y: 42, status: "reserved" },
      { id: "t5", sectionId: "sec-main", label: "Family", seats: 8, shape: "large", x: 48, y: 38, status: "empty" },
      { id: "t6", sectionId: "sec-main", label: "Center 1", seats: 4, shape: "rect", x: 8, y: 68, status: "occupied" },
      { id: "t7", sectionId: "sec-main", label: "High-top", seats: 2, shape: "round", x: 32, y: 70, status: "occupied" },
      { id: "t8", sectionId: "sec-main", label: "Patio door", seats: 4, shape: "rect", x: 52, y: 68, status: "reserved" },
    ],
    categories: [
      { id: "c-all", nameKey: "menu.cat.all" },
      { id: "c-hot", nameKey: "menu.cat.hot" },
      { id: "c-cold", nameKey: "menu.cat.cold" },
      { id: "c-pastries", nameKey: "menu.cat.pastries" },
    ],
    modifierGroups: [
      {
        id: "mg-milk",
        name: "Choose milk",
        nameKey: "menu.milk",
        selection: "single",
        options: [
          { id: "m-whole", name: "Whole milk", nameKey: "menu.whole", priceDelta: 0 },
          { id: "m-oat", name: "Oat milk", nameKey: "menu.oat", priceDelta: 0.5 },
          { id: "m-almond", name: "Almond milk", nameKey: "menu.almond", priceDelta: 0.5 },
          { id: "m-soy", name: "Soy milk", nameKey: "menu.soy", priceDelta: 0.5 },
        ],
      },
      {
        id: "mg-shot",
        name: "Extras",
        nameKey: "menu.extras",
        selection: "single",
        options: [
          { id: "x-none", name: "No extra", nameKey: "menu.noExtra", priceDelta: 0 },
          { id: "x-shot", name: "Extra shot", nameKey: "menu.extraShot", priceDelta: 1.5 },
        ],
      },
    ],
    menuItems: [
      { id: "mi1", categoryId: "c-hot", nameKey: "menu.espresso", name: "Espresso Double", basePrice: 3.5, allergens: ["D"], modifierGroupIds: ["mg-shot"] },
      { id: "mi2", categoryId: "c-hot", nameKey: "menu.cappuccino", name: "Cappuccino Regular", basePrice: 4.5, allergens: ["D"], modifierGroupIds: ["mg-milk", "mg-shot"] },
      { id: "mi3", categoryId: "c-hot", nameKey: "menu.latte", name: "Vanilla Latte", basePrice: 4.8, allergens: ["D"], modifierGroupIds: ["mg-milk"] },
      { id: "mi4", categoryId: "c-hot", nameKey: "menu.mocha", name: "Hazelnut Mocha", basePrice: 5.2, allergens: ["D", "N"], modifierGroupIds: ["mg-milk"] },
      { id: "mi5", categoryId: "c-hot", nameKey: "menu.drip", name: "Brewed Drip Coffee", basePrice: 3.0, allergens: [], modifierGroupIds: [] },
      { id: "mi6", categoryId: "c-hot", nameKey: "menu.flat", name: "Flat White", basePrice: 4.5, allergens: ["D"], modifierGroupIds: ["mg-milk"] },
      { id: "mi7", categoryId: "c-hot", nameKey: "menu.chai", name: "Chai Tea Latte", basePrice: 5.0, allergens: ["D", "G"], modifierGroupIds: ["mg-milk"] },
      { id: "mi8", categoryId: "c-hot", nameKey: "menu.matcha", name: "Warm Matcha Brew", basePrice: 5.2, allergens: ["D"], modifierGroupIds: ["mg-milk"] },
    ],
    orders: [
      {
        id: "ord_seed_1",
        number: 2045,
        tableId: "t2",
        tableLabel: "Window 4",
        waiterId: "s2",
        waiterName: "Sarah Smith",
        status: "submitted",
        lines: [
          {
            id: "line_s1a",
            menuItemId: "mi6",
            name: "Flat White",
            quantity: 2,
            unitPrice: 5.0,
            modifierLabels: ["Oat milk (+$0.50)"],
            kitchenNote: "OAT MILK ONLY — customer allergy",
            allergyNote: true,
            lineTotal: 10.0,
          },
          {
            id: "line_s1b",
            menuItemId: "mi5",
            name: "Brewed Drip Coffee",
            quantity: 1,
            unitPrice: 3.0,
            modifierLabels: [],
            kitchenNote: "Extra hot water on side",
            lineTotal: 3.0,
          },
        ],
        subtotal: 13.0,
        taxRate: 0.08,
        tax: 1.04,
        total: 14.04,
        createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
        submittedAt: new Date(Date.now() - 3 * 60_000).toISOString(),
      },
      {
        id: "ord_seed_2",
        number: 2046,
        tableId: "t6",
        tableLabel: "Center 1",
        waiterId: "s5",
        waiterName: "Mark Evans",
        status: "submitted",
        lines: [
          {
            id: "line_s2a",
            menuItemId: "mi2",
            name: "Cappuccino Regular",
            quantity: 1,
            unitPrice: 4.5,
            modifierLabels: ["Whole milk"],
            lineTotal: 4.5,
          },
          {
            id: "line_s2b",
            menuItemId: "mi7",
            name: "Chai Tea Latte",
            quantity: 1,
            unitPrice: 5.5,
            modifierLabels: ["Oat milk (+$0.50)"],
            kitchenNote: "Note: Oat milk",
            lineTotal: 5.5,
          },
        ],
        subtotal: 10.0,
        taxRate: 0.08,
        tax: 0.8,
        total: 10.8,
        createdAt: new Date(Date.now() - 2 * 60_000).toISOString(),
        submittedAt: new Date(Date.now() - 90_000).toISOString(),
      },
      {
        id: "ord_seed_3",
        number: 2047,
        tableId: "t7",
        tableLabel: "High-top",
        waiterId: "s2",
        waiterName: "Sarah Smith",
        status: "submitted",
        lines: [
          {
            id: "line_s3a",
            menuItemId: "mi4",
            name: "Hazelnut Mocha",
            quantity: 1,
            unitPrice: 5.7,
            modifierLabels: ["Soy milk (+$0.50)"],
            kitchenNote: "Note: Decaf",
            lineTotal: 5.7,
          },
          {
            id: "line_s3b",
            menuItemId: "mi8",
            name: "Warm Matcha Brew",
            quantity: 1,
            unitPrice: 5.2,
            modifierLabels: ["Whole milk"],
            lineTotal: 5.2,
          },
        ],
        subtotal: 10.9,
        taxRate: 0.08,
        tax: 0.87,
        total: 11.77,
        createdAt: new Date(Date.now() - 8 * 60_000).toISOString(),
        submittedAt: new Date(Date.now() - 7 * 60_000).toISOString(),
      },
    ],
    tickets: [
      {
        id: "tkt_seed_1",
        orderId: "ord_seed_1",
        tableLabel: "Window 4",
        waiterName: "Sarah Smith",
        status: "pending",
        lines: [
          { qty: 2, name: "Flat White", note: "OAT MILK ONLY — customer allergy", allergy: true },
          { qty: 1, name: "Brewed Drip Coffee", note: "Extra hot water on side" },
        ],
        createdAt: new Date(Date.now() - 3 * 60_000).toISOString(),
      },
      {
        id: "tkt_seed_2",
        orderId: "ord_seed_2",
        tableLabel: "Center 1",
        waiterName: "Mark Evans",
        status: "pending",
        lines: [
          { qty: 1, name: "Cappuccino Regular" },
          { qty: 1, name: "Chai Tea Latte", note: "Note: Oat milk" },
        ],
        createdAt: new Date(Date.now() - 90_000).toISOString(),
      },
      {
        id: "tkt_seed_3",
        orderId: "ord_seed_3",
        tableLabel: "High-top",
        waiterName: "Sarah Smith",
        status: "preparing",
        lines: [
          { qty: 1, name: "Hazelnut Mocha", note: "Note: Decaf" },
          { qty: 1, name: "Warm Matcha Brew" },
        ],
        createdAt: new Date(Date.now() - 7 * 60_000).toISOString(),
        startedAt: new Date(Date.now() - 5 * 60_000).toISOString(),
      },
    ],
    payments: [],
    activity: [
      {
        id: "a1",
        titleKey: "activity.seed1",
        title: "Order #2044 completed",
        actor: "Sarah Smith (Waiter)",
        at: new Date(Date.now() - 5 * 60_000).toISOString(),
        tone: "success",
      },
      {
        id: "a2",
        titleKey: "activity.seed2",
        title: "Table Window 4 occupied",
        actor: "Staff action",
        at: new Date(Date.now() - 12 * 60_000).toISOString(),
        tone: "danger",
      },
    ],
  };
}
